In [4]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
docs = pd.read_csv("example_train.csv")
docs

Document      Class
0         Teclov is a great educational institution.  education
1            Educational greatness depends on ethics  education
2  A story of great ethics and educational greatness  education
3                           Sholey is a great cinema     cinema
4                   good movie depends on good story     cinema

In [21]:
docs["Class"] = docs["Class"].map({"cinema":0,"education":1}) 

numpy_array = docs.to_numpy()
X = numpy_array[:,0]
y = numpy_array[:,1]
y = y.astype("int")
print(X)
print(y)

['Teclov is a great educational institution.'
 'Educational greatness depends on ethics'
 'A story of great ethics and educational greatness'
 'Sholey is a great cinema' 'good movie depends on good story']
[1 1 1 0 0]


In [22]:
from sklearn.feature_extraction.text import CountVectorizer

vec = CountVectorizer()

In [24]:
vec.fit(X)
vec.vocabulary_

{'teclov': 15,
 'is': 9,
 'great': 6,
 'educational': 3,
 'institution': 8,
 'greatness': 7,
 'depends': 2,
 'on': 12,
 'ethics': 4,
 'story': 14,
 'of': 11,
 'and': 0,
 'sholey': 13,
 'cinema': 1,
 'good': 5,
 'movie': 10}

In [25]:
vec = CountVectorizer(stop_words = "english")
vec.fit(X)
vec.vocabulary_

{'teclov': 11,
 'great': 5,
 'educational': 2,
 'institution': 7,
 'greatness': 6,
 'depends': 1,
 'ethics': 3,
 'story': 10,
 'sholey': 9,
 'cinema': 0,
 'good': 4,
 'movie': 8}

In [28]:
#another way to represent the vocabulary
print(vec.get_feature_names())
print(len(vec.get_feature_names()))

['cinema', 'depends', 'educational', 'ethics', 'good', 'great', 'greatness', 'institution', 'movie', 'sholey', 'story', 'teclov']
12


In [29]:
X_transformed = vec.transform(X)
X_transformed

<5x12 sparse matrix of type '<class 'numpy.int64'>'
	with 20 stored elements in Compressed Sparse Row format>

In [30]:
print(X_transformed)

  (0, 2)	1
  (0, 5)	1
  (0, 7)	1
  (0, 11)	1
  (1, 1)	1
  (1, 2)	1
  (1, 3)	1
  (1, 6)	1
  (2, 2)	1
  (2, 3)	1
  (2, 5)	1
  (2, 6)	1
  (2, 10)	1
  (3, 0)	1
  (3, 5)	1
  (3, 9)	1
  (4, 1)	1
  (4, 4)	2
  (4, 8)	1
  (4, 10)	1


In [31]:
x = X_transformed.toarray()
x

array([[0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1],
       [0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 1, 0]], dtype=int64)

In [33]:
pd.DataFrame(x,columns = vec.get_feature_names())

cinema  depends  educational  ethics  good  great  greatness  institution  \
0       0        0            1       0     0      1          0            1   
1       0        1            1       1     0      0          1            0   
2       0        0            1       1     0      1          1            0   
3       1        0            0       0     0      1          0            0   
4       0        1            0       0     2      0          0            0   

   movie  sholey  story  teclov  
0      0       0      0       1  
1      0       0      0       0  
2      0       0      1       0  
3      0       1      0       0  
4      1       0      1       0

In [42]:
data = {"document":["very good educational institution"],
        "Class":["education"]}

test_docs = pd.DataFrame(data)
test_docs

document      Class
0  very good educational institution  education

In [43]:
test_docs["Class"] = test_docs.Class.map({"education":1,"cinema":"0"})

In [44]:
test_docs

document Class
0  very good educational institution     1

In [47]:
test_array = test_docs.to_numpy()
X_test = test_array[:,0]
y_test = test_array[:,1]
y_test = y_test.astype("int")
print(X_test,y_test)

['very good educational institution'] [1]


In [49]:
X_test_transform = vec.transform(X_test)

In [51]:
x_test = X_test_transform.toarray()
x_test

array([[0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0]], dtype=int64)

In [53]:
#multinomial Nb
from sklearn.naive_bayes import MultinomialNB

mb = MultinomialNB()
mb.fit(x,y)
mb.predict_proba(x_test)

array([[0.32808399, 0.67191601]])

In [54]:
mnb_proba = mb.predict_proba(x_test)

pd.DataFrame(mnb_proba,columns = ["cinema","education"])

cinema  education
0  0.328084   0.671916

In [55]:
from sklearn.naive_bayes import BernoulliNB

Bnb = BernoulliNB()

Bnb.fit(x,y)

Bnb_proba = Bnb.predict_proba(x_test)

pd.DataFrame(Bnb_proba,columns = ["cinema","education"])

cinema  education
0  0.232637   0.767363